я прописал вызов функции в страницы с VPN но в консоли браузера видна ошибка CORS при попытке отправить POST-запрос на https://functions.poehali.dev/540fd4ac-812f-4cac-b72b-9ae038b22774/event
pp-min-2.js:1 Error handler not initialized: page is not in an iframe
client:745  WebSocket connection to 'wss://preview--vds-rating-portal.poehali.dev/?token=4hldEb-5Z_F9' failed: Error during WebSocket handshake: Unexpected response code: 403
createConnection @ client:745
telemetry-min.js:1 Download the React DevTools for a better development experience: https://reactjs.org/link/react-devtools
telemetry-min.js:1  ⚠️ React Router Future Flag Warning: React Router will begin wrapping state updates in `React.startTransition` in v7. You can use the `v7_startTransition` future flag to opt-in early. For more information, see https://reactrouter.com/v6/upgrading/future#v7_starttransition.
_0x416cf8.<computed>.console.<computed> @ telemetry-min.js:1
telemetry-min.js:1  ⚠️ React Router Future Flag Warning: Relative route resolution within Splat routes is changing in v7. You can use the `v7_relativeSplatPath` future flag to opt-in early. For more information, see https://reactrouter.com/v6/upgrading/future#v7_relativesplatpath.
_0x416cf8.<computed>.console.<computed> @ telemetry-min.js:1
vpn:1  Access to fetch at 'https://functions.poehali.dev/540fd4ac-812f-4cac-b72b-9ae038b22774/event' from origin 'https://preview--vds-rating-portal.poehali.dev' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.
functions.poehali.dev/540fd4ac-812f-4cac-b72b-9ae038b22774/event:1   Failed to load resource: net::ERR_FAILED
telemetry-min.js:1  Error tracking event: TypeError: Failed to fetch
    at window.<computed> (telemetry-min.js:1:9296)
    at trackEvent (eventTracker.ts:33:3)
    at useTrackEvent.ts:12:5
    at Vpn.tsx:18:5
    at commitHookEffectListMount (react-dom.development.js:23189:26)
    at commitPassiveMountOnFiber (react-dom.development.js:24965:13)
    at commitPassiveMountEffects_complete (react-dom.development.js:24930:9)
    at commitPassiveMountEffects_begin (react-dom.development.js:24917:7)
    at commitPassiveMountEffects (react-dom.development.js:24905:3)
    at flushPassiveEffectsImpl (react-dom.development.js:27078:3)
_0x416cf8.<computed>.console.<computed> @ telemetry-min.js:1
vpn:1  Access to fetch at 'https://functions.poehali.dev/540fd4ac-812f-4cac-b72b-9ae038b22774/event' from origin 'https://preview--vds-rating-portal.poehali.dev' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.
functions.poehali.dev/540fd4ac-812f-4cac-b72b-9ae038b22774/event:1   Failed to load resource: net::ERR_FAILED
telemetry-min.js:1  Error tracking event: TypeError: Failed to fetch
    at window.<computed> (telemetry-min.js:1:9296)
    at trackEvent (eventTracker.ts:33:3)
    at useTrackEvent.ts:12:5
    at Vpn.tsx:18:5
    at commitHookEffectListMount (react-dom.development.js:23189:26)
    at commitPassiveMountOnFiber (react-dom.development.js:24965:13)
    at commitPassiveMountEffects_complete (react-dom.development.js:24930:9)
    at commitPassiveMountEffects_begin (react-dom.development.js:24917:7)
    at commitPassiveMountEffects (react-dom.development.js:24905:3)
    at flushPassiveEffectsImpl (react-dom.development.js:27078:3)
_0x416cf8.<computed>.console.<computed> @ telemetry-min.js:1
vpn:1  Access to fetch at 'https://functions.poehali.dev/540fd4ac-812f-4cac-b72b-9ae038b22774/event' from origin 'https://preview--vds-rating-portal.poehali.dev' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.
functions.poehali.dev/540fd4ac-812f-4cac-b72b-9ae038b22774/event:1   Failed to load resource: net::ERR_FAILED
telemetry-min.js:1  Error tracking event: TypeError: Failed to fetch
    at window.<computed> (telemetry-min.js:1:9296)
    at trackEvent (eventTracker.ts:33:3)
    at useTrackEvent.ts:12:5
    at Vpn.tsx:18:5
    at commitHookEffectListMount (react-dom.development.js:23189:26)
    at commitPassiveMountOnFiber (react-dom.development.js:24965:13)
    at commitPassiveMountEffects_complete (react-dom.development.js:24930:9)
    at commitPassiveMountEffects_begin (react-dom.development.js:24917:7)
    at commitPassiveMountEffects (react-dom.development.js:24905:3)
    at flushPassiveEffectsImpl (react-dom.development.js:27078:3)
_0x416cf8.<computed>.console.<computed> @ telemetry-min.js:1
client:755  WebSocket connection to 'wss://localhost:5173/?token=4hldEb-5Z_F9' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
createConnection @ client:755
telemetry-min.js:1  [vite] failed to connect to websocket.
your current setup:
  (browser) preview--vds-rating-portal.poehali.dev/ <--[HTTP]--> localhost:5173/ (server)
  (browser) preview--vds-rating-portal.poehali.dev:/ <--[WebSocket (failing)]--> localhost:5173/ (server)
Check out your Vite / network configuration and https://vite.dev/config/server-options.html#server-hmr .
_0x416cf8.<computed>.console.<computed> @ telemetry-min.js:1
connect @ client:765